image: Visual Studio 2017

platform: Any CPU
configuration: Release

shallow_clone: true
skip_tags: true

environment:
  GITHUB_AUTH_TOKEN:
    secure: a+daW6wCxNjiC19/k6jLSgweptfO1hx8779M6wDFPaEA/Hg14D6jVqMBw/mO27Sq

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

init:
  - ps: |
      If (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        $env:IS_NOT_PR = "true"
      }

before_build:
  - nuget restore src\CrossSectionPlugin.sln

build:
  project: src\CrossSectionPlugin.sln

artifacts:
  - path: src\CrossSectionPlugin\deploy\Release\CrossSectionPlugin.plugin
    name: ThePlugin
    type: file

deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: CrossSection plugin $(APPVEYOR_BUILD_VERSION)
    description: ''
    artifact: ThePlugin
    auth_token: $(GITHUB_AUTH_TOKEN)
    on:
      is_not_pr: true
